del /Q /S *.~*
del /Q /S *.bak
del /Q /S *.tmp
del /Q /S *.#0*
del /Q /S *.pch
del /Q /S *.ils
del /Q /S *.ild
del /Q /S *.ilf
del /Q /S *.ilc
del /Q /S *.tds
del /Q /S *.ipch
del /Q /S *.iobj
del /Q /S *.ipdb